---

# forced os variables
- name: forced os variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ role_name }}-{{ inventory_hostname }}.yml'
        - '{{ role_name }}-{{ inventory_hostname_short }}.yml'
        - '{{ role_name }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_machine | default("none") }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_release | default(0) }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_version | default(0) }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version | default(0) }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'main.yml'
      paths:
        - '{{ inventory_dir }}/vars'
        - 'vars'
  when: dma_enabled
        and ansible_os_family | string in dma_os_family_supported
  tags: [ dma ]

# packages
- name: packages (freebsd)
  pkgng:
    name: '{{ dma_packages_freebsd | default([]) }}'
    state: '{{ dma_packages_freebsd_state | default("latest") }}'
    cached: '{{ dma_packages_freebsd_cached | default(false) }}'
  when: dma_enabled
        and ansible_os_family | string in dma_os_family_supported
        and ansible_os_family == 'FreeBSD'
  tags: [ dma ]

# mailer config
- name: mail (freebsd directory)
  file:
    dest: '{{ dma_mailer_cfg_file | dirname }}'
    mode: '{{ dma_dir_mode }}'
    state: directory
  when: dma_enabled
        and ansible_os_family | string in dma_os_family_supported
        and ansible_os_family == 'FreeBSD'
  tags: [ dma ]

- name: mailer config (freebsd template)
  template:
    dest: '{{ dma_mailer_cfg_file }}'
    src: "{{ lookup('first_found', params) }}"
    #
    mode: '{{ dma_mailer_cfg_file_mode | default(dma_file_mode) }}'
    owner: '{{ dma_mailer_cfg_file_owner | default(dma_owner) }}'
    group: '{{ dma_mailer_cfg_file_group | default(dma_group) }}'
    backup: '{{ dma_mailer_cfg_file_backup | default(dma_backup) }}'
    validate: '{{ dma_mailer_cfg_file_validate | default(omit) }}'
  vars:
    tpl_default: '{{ dma_mailer_cfg_file | basename }}'
    tpl_presence: '{{ dma_mailer_cfg_file_template | default(tpl_default) }}'
    params:
      files:
        - '{{ tpl_presence }}.{{ inventory_hostname }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}-{{ ansible_distribution_version | default(0) }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}-{{ ansible_distribution_major_version | default(0) }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}.j2'
        - '{{ tpl_presence }}.{{ ansible_os_family }}.j2'
        - '{{ tpl_presence }}.j2'
        - '{{ tpl_presence }}.j2.in' # role default
      paths:
        - '{{ inventory_dir }}/templates'
        - 'templates'
  when: dma_enabled
        and ansible_os_family | string in dma_os_family_supported
  tags: [ dma ]

# config
- name: dma config (template)
  template:
    dest: '{{ dma_cfg_file }}'
    src: "{{ lookup('first_found', params) }}"
    #
    mode: '{{ dma_cfg_file_mode | default(dma_file_mode) }}'
    owner: '{{ dma_cfg_file_owner | default(dma_owner) }}'
    group: '{{ dma_cfg_file_group | default(dma_group) }}'
    backup: '{{ dma_cfg_file_backup | default(dma_backup) }}'
    validate: '{{ dma_cfg_file_validate | default(omit) }}'
  vars:
    tpl_default: '{{ dma_cfg_file | basename }}'
    tpl_presence: '{{ dma_cfg_file_template | default(tpl_default) }}'
    params:
      files:
        - '{{ tpl_presence }}.{{ inventory_hostname }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}-{{ ansible_distribution_version | default(0) }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}-{{ ansible_distribution_major_version | default(0) }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}.j2'
        - '{{ tpl_presence }}.{{ ansible_os_family }}.j2'
        - '{{ tpl_presence }}.j2'
        - '{{ tpl_presence }}.j2.in' # role default
      paths:
        - '{{ inventory_dir }}/templates'
        - 'templates'
  when: dma_enabled
        and ansible_os_family | string in dma_os_family_supported
  tags: [ dma ]

- name: dma auth (template)
  template:
    dest: '{{ dma_auth_file }}'
    src: "{{ lookup('first_found', params) }}"
    #
    mode: '{{ dma_auth_file_mode | default(dma_file_mode) }}'
    owner: '{{ dma_auth_file_owner | default(dma_owner) }}'
    group: '{{ dma_auth_file_group | default(dma_group) }}'
    backup: '{{ dma_auth_file_backup | default(dma_backup) }}'
    validate: '{{ dma_auth_file_validate | default(omit) }}'
  vars:
    tpl_default: '{{ dma_auth_file | basename }}'
    tpl_presence: '{{ dma_auth_file_template | default(tpl_default) }}'
    params:
      files:
        - '{{ tpl_presence }}.{{ inventory_hostname }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}-{{ ansible_distribution_version | default(0) }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}-{{ ansible_distribution_major_version | default(0) }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}.j2'
        - '{{ tpl_presence }}.{{ ansible_os_family }}.j2'
        - '{{ tpl_presence }}.j2'
        - '{{ tpl_presence }}.j2.in' # role default
      paths:
        - '{{ inventory_dir }}/templates'
        - 'templates'
  when: dma_enabled
        and ansible_os_family | string in dma_os_family_supported
  tags: [ dma ]

- name: dma aliases (template)
  template:
    dest: '{{ dma_aliases_file }}'
    src: "{{ lookup('first_found', params) }}"
    #
    mode: '{{ dma_aliases_file_mode | default(dma_file_mode) }}'
    owner: '{{ dma_aliases_file_owner | default(dma_owner) }}'
    group: '{{ dma_aliases_file_group | default(dma_group) }}'
    backup: '{{ dma_aliases_file_backup | default(dma_backup) }}'
    validate: '{{ dma_aliases_file_validate | default(omit) }}'
  vars:
    tpl_default: '{{ dma_aliases_file | basename }}'
    tpl_presence: '{{ dma_aliases_file_template | default(tpl_default) }}'
    params:
      files:
        - '{{ tpl_presence }}.{{ inventory_hostname }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}-{{ ansible_distribution_version | default(0) }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}-{{ ansible_distribution_major_version | default(0) }}.j2'
        - '{{ tpl_presence }}.{{ ansible_distribution }}.j2'
        - '{{ tpl_presence }}.{{ ansible_os_family }}.j2'
        - '{{ tpl_presence }}.j2'
        - '{{ tpl_presence }}.j2.in' # role default
      paths:
        - '{{ inventory_dir }}/templates'
        - 'templates'
  when: dma_enabled
        and ansible_os_family | string in dma_os_family_supported
  tags: [ dma ]

- name: dma config (freebsd-update.conf IgnorePaths)
  lineinfile:
    path: '{{ dma_freebsd_update_cfg_file }}'
    line: 'IgnorePaths {{ dma_cfg_file }}'
    regex: '^IgnorePaths {{ dma_cfg_file }}'
    insertafter: '^IgnorePaths.*$'
    state: present
    backup: yes
  when: dma_enabled
        and ansible_os_family | string in dma_os_family_supported
        and ansible_os_family == 'FreeBSD'
  tags: [ dma ]

# vim: set ft=yaml.ansible sw=2 ts=2 et colorcolumn=160 :
# eof
